checks:
  php: true
filter:
  excluded_paths:
    - tests/*
build:
  environment:
    php: 8.2.0
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run src/*
    my-tests:
      environment:
        php:
          version: 8.2.0
          pecl_extensions:
            - swoole-4.8.13
      dependencies:
        before:
          - composer install
      tests:
        override:
          - composer test
    coverage:
      tests:
        override:
          - command: composer test
            coverage:
              file: coverage/coverage.xml
              format: clover
